@startuml

class main {
    void main()
}

main *-- TabsScreen

TabsScreen *-- CategoriesScreen
TabsScreen *-- FiltersScreen
TabsScreen *-- MealsScreen
TabsScreen *-- MainDrawer
TabsScreen *-- Meal
TabsScreen *-- PersistFavorites

CategoriesScreen *-- Meal
CategoriesScreen *-- CategoryGridItem
CategoriesScreen *-- MealsScreen
CategoriesScreen *-- Category

MealsScreen *-- MealDetailsScreen
MealsScreen *-- MealItem

MealDetailsScreen *-- Meal

MealItem *-- MealItemTrait
MealItem *-- Meal

CategoryGridItem *-- Category
@enduml