@startuml

class main {
    void main()
}

class CategoriesScreen{}
class TabsScreen{}
class MealsScreen{}
class FiltersScreen{}
class MealDetailsScreen{}

class MealItem {
    Key : key
    Meal : meal
    Function : onSelectMeal
}
class MealItemTrait {
    Key key
    IconData icon
    String label
}
class MainDrawer{}
class CategoryGridItem{}

class Meal{}
class Category{}

main *-- TabsScreen

TabsScreen *-- CategoriesScreen
TabsScreen *-- FiltersScreen
TabsScreen *-- MealsScreen
TabsScreen *-- MainDrawer
TabsScreen *-- Meal

CategoriesScreen *-- Meal
CategoriesScreen *-- CategoryGridItem
CategoriesScreen *-- MealsScreen
CategoriesScreen *-- Category

MealsScreen *-- MealDetailsScreen
MealsScreen *-- MealItem

MealDetailsScreen *-- Meal

MealItem *-- MealItemTrait
MealItem *-- Meal

CategoryGridItem *-- Category
@enduml